### ISSUE TITLE
Has this project stopped or just paused?

### ISSUE THREAD

**Issue by Angel-del-dev** [RezSat/Ysharp-v4#1]
I am a programmer who likes learning about different languages and as a part of a challenge, i am looking for potential new languages to code with, nothing really serious, just for fun.

I was just wondering whether this project is going to be resumed in the future.

**Comment by RezSat** [comment]
Oh I ended up changing the name and make it another language .., Now it's
known as Ceylonicus...you can test it on:https://www.ceylonicus.vercel.app
and the repo is https://www.github.com/RezSat/Ceylonicus. It's like the
Ysharp v7 ...so yeah..


By the way..I really need to thank u for Ur interest in my little work.. 😀
